#+TILTE:LiquidZulu's Doom Config
#+PROPERTY: header-args :tangle config.el
/This file is best viewed in [[https://www.gnu.org/software/emacs/][emacs]]!/

* Introduction
This is my config for [[https://github.com/hlissner/doom-emacs][Doom Emacs]]
#+begin_quote
...a configuration framework for GNU Emacs tailored for Emacs bankruptcy veterans who want less framework in their frameworks, a modicum of stability (and reproducibility) from their package manager, and the performance of a hand rolled config (or better). It can be a foundation for your own config or a resource for Emacs enthusiasts to learn more about our favorite operating system.
#+end_quote
** Modifying this config
=README.org= contains a number of source blocks that may be modified at will, then do a local refresh (=C-c C-c=) and run =org-babel-tangle= (=C-c C-v t=) with the point on the above =#+PROPERTY= tag.
** Why Doom?
You will notice from a perusing of =init.el= that I have disabled [[https://www.emacswiki.org/emacs/Evil][Evil Mode]], so I am clearly not on Doom for the vi bindings. I use Doom for the speed and to avoid bankruptcy --- vanilla bindings are good enough in most areas though I have modified the movement to make sense on Colemak-DHm.

* Lexical Binding
Enable Lexical Binding
#+begin_src elisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

* Helper Functions
I got most of these from [[https://dustinlacewell.github.io/emacs.d/][Dustin Lacewell's init.el]]. I dont use most of these but its nice to have them if im going to be taxing things from his init.
** TODO New Footnote Template
#+begin_src elisp
(defun footnote-template ()
  (if (and
       (string=
        (substring
         (thing-at-point 'line t)
         0
         4)
        "[fn:")
       (string=
        (substring
         (thing-at-point 'line t)
         -3
         nil)
        "]\n")
       )
      (lambda () (interactive)
        (insert "[[][]] ([[][archived]])")
        (dotimes
            (i 19)
          (backward-char)))))
#+end_src

** slugify
Based on =remove-vowel= from http://xahlee.info/emacs/emacs/elisp_command_working_on_string_or_region.html
#+begin_src elisp
(defun slugify ($string &optional $from $to)
  "Slugify a string

When called interactively, work on current paragraph or text selection.

When called in lisp code, if $string is non-nil, returns a changed string.
If $string nil, change the text in the region between positions $from $to."
  (interactive
   (if (use-region-p)
       (list nil (region-beginning) (region-end))
     (let ((bds (bounds-of-thing-at-point 'paragraph)) )
       (list nil (car bds) (cdr bds)) ) ) )

  (let (workOnStringP inputStr outputStr)
    (setq workOnStringP (if $string t nil))
    (setq inputStr (if workOnStringP $string (buffer-substring-no-properties $from $to)))
    (setq outputStr
          (let ((case-fold-search t))
            (replace-regexp-in-string  "[^a-z0-9\-]+" ""  (replace-regexp-in-string "[ ]+" "\-" (downcase inputStr)))))

    (if workOnStringP
        outputStr
      (save-excursion
        (delete-region $from $to)
        (goto-char $from)
        (insert outputStr) )) ) )
#+end_src

** :function
Make non-interactive functions out of forms or a symbol.
#+begin_src elisp
(defmacro :function (&rest body)
  (if (->> body length (< 1))
      `(lambda () ,@body)
    (pcase (car body)
      ;; command symbol
      ((and v (pred commandp))
       `(lambda () (call-interactively (quote ,v))))
      ;; function symbol
      ((and v (pred symbolp))
       `(lambda () (,v)))
      ;; quoted command symbol
      ((and v (pred consp) (guard (eq 'quote (car v))) (pred commandp (cadr v)))
       `(lambda () (call-interactively ,v)))
      ;; quoted function symbol
      ((and v (pred consp) (guard (eq 'quote (car v))))
       `(lambda () (,(cadr v))))
      ;; body forms
      (_ `(lambda () ,@body) ))))
#+end_src

** :command
Make interactive commands out of forms or a symbol.
#+begin_src elisp
(defmacro :command (&rest body)
  (if (->> body length (< 1))
      `(lambda () (interactive) ,@body)
    (pcase (car body)
      ;; command symbol
      ((and v (pred commandp))
       `(lambda () (interactive) (call-interactively (quote ,v))))
      ;; function symbol
      ((and v (pred symbolp))
       `(lambda () (interactive) (,v)))
      ;; quoted command symbol
      ((and v (pred consp) (guard (eq 'quote (car v))) (pred commandp (cadr v)))
       `(lambda () (interactive) (call-interactively ,v)))
      ;; quoted function symbol
      ((and v (pred consp) (guard (eq 'quote (car v))))
       `(lambda () (interactive) (,(cadr v))))
      ;; body forms
      (_ `(lambda () (interactive) ,@body) ))))
#+end_src

** :after
Defer some forms until the given package is loaded.
#+begin_src elisp
(defmacro :after (package &rest body)
  "A simple wrapper around `with-eval-after-load'."
  (declare (indent defun))
  `(with-eval-after-load ',package ,@body))
#+end_src

** :hook
Register some forms or a symbol with a hook.
#+begin_src elisp
(defmacro :hook (hook-name &rest body)
  "A simple wrapper around `add-hook'"
  (declare (indent defun))
  (let* ((hook-name (format "%s-hook" (symbol-name hook-name)))
         (hook-sym (intern hook-name))
         (first (car body))
         (local (eq :local first))
         (body (if local (cdr body) body))
         (first (car body))
         (body (if (consp first)
                   (if (eq (car first) 'quote)
                       first
                     `(lambda () ,@body))
                 `',first)))
    `(add-hook ',hook-sym ,body nil ,local)))
#+end_src

** :push
A wrapper around add-to-list.
#+begin_src elisp
(defmacro :push (sym &rest body)
  (declare (indent defun))
  (if (consp body)
      `(setq ,sym (-snoc ,sym ,@body))
    `(add-to-list ,sym ,body)))
#+end_src

** :bind
Bind some forms or a symbol to a key. (I use map! instead)
#+begin_src elisp
(defmacro :bind (key &rest body)
  (declare (indent defun))
  (pcase key
    ;; kbd string resolving symbol
    ((and k (pred symbolp) (pred boundp) (guard (stringp (eval key))))
     `(global-set-key (kbd ,(eval key)) ,(eval `(:command ,@body))))
    ;; partial mode symbol
    ((pred symbolp)
     (let ((mode (intern (format "%s-map" key)))
           (key (eval (car body)))
           (body (eval `(:command ,@(cdr body)))))
       `(define-key ,mode (kbd ,key) ,body)))
    ;; global binding
    (_ `(global-set-key (kbd ,key) ,(eval `(:command ,@body))))))
#+end_src

** :enable-minor-mode
https://github.com/prettier/prettier-emacs#usage-with-web-mode
#+begin_src elisp
(defun :enable-minor-mode (my-pair)
  "Enable minor mode if filename match the regexp.  MY-PAIR is a cons cell (regexp . minor-mode)."
  (if (buffer-file-name)
      (if (string-match (car my-pair) buffer-file-name)
      (funcall (cdr my-pair)))))
#+end_src

* Settings

** email
Email and username, some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+begin_src elisp
(setq user-full-name "LiquidZulu"
      user-mail-address "liquidzulu@pm.me")
#+end_src
** Image size
Sets inline images to be 500 wide
#+begin_src elisp
(setq org-image-actual-width 500)
#+end_src
** Theme
#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src

** custom-set-faces
#+begin_src elisp
(custom-set-faces!
 '(rainbow-delimiters-depth-1-face :foreground "#FF5F5C")
 '(rainbow-delimiters-depth-2-face :foreground "#FFF1C7")
 '(rainbow-delimiters-depth-3-face :foreground "#5E807F")
 '(rainbow-delimiters-depth-4-face :foreground "#33FFEB")
 '(rainbow-delimiters-depth-5-face :foreground "#FF5D38")
 '(rainbow-delimiters-depth-6-face :foreground "#FFC72E")
 '(rainbow-delimiters-depth-7-face :foreground "#75FFD6")
 '(rainbow-delimiters-depth-8-face :foreground "#2996F5")
 '(rainbow-delimiters-depth-9-face :foreground "#FFFB7A")
 '(outline-1 :font "Cubano:pixelsize=32")
 '(outline-2 :font "Cubano:pixelsize=30")
 '(outline-3 :font "Cubano:pixelsize=28")
 '(outline-4 :font "Cubano:pixelsize=28")
 '(outline-5 :font "Cubano:pixelsize=28")
 '(outline-6 :font "Cubano:pixelsize=28")
 '(outline-7 :font "Cubano:pixelsize=28")
 '(outline-8 :font "Cubano:pixelsize=28")
 )
#+end_src

** Font stuff
*** Font-Family
#+begin_src elisp
; https://github.com/doomemacs/doomemacs/issues/5948#issuecomment-1004253858
(setq
 normal-font (cl-find-if #'doom-font-exists-p
                         '(
                           "mononoki"
                           "JetBrainsMono Nerd Font"
                           "NotoSerif Nerd Font"
                           "monospace")))
(setq
 doom-font      (font-spec :family normal-font :size 24)
 doom-big-font  (font-spec :family normal-font :size 32))
#+end_src

** Org settings
*** headline levels
Makes it so that I can style exported html, no clue why it isn't higher by default.
#+begin_src elisp
(setq org-export-headline-levels 512)
#+end_src
*** image settings
Display images on startup
#+begin_src elisp
(setq org-startup-with-inline-images t)
#+end_src
Set image width to 500
#+begin_src elisp
(setq org-image-actual-width 500)
#+end_src

** line number style
This determines the style of line numbers in effect. If set to =nil=, line numbers are disabled. For relative line numbers, set this to =relative=.
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src

** various misc setings
Blah
#+begin_src elisp
(setq delete-by-moving-to-trash t)           ; Delete files to trash
(setq tab-width 4)                            ; Set width for tabs
(setq uniquify-buffer-name-style 'forward)    ; Uniquify buffer names
(setq window-combination-resize t)            ; take new window space from all other windows (not just current)
(setq x-stretch-cursor t)                    ; Stretch cursor to the glyph width

(setq undo-limit 80000000)                    ; Raise undo-limit to 80Mb
(setq evil-want-fine-undo t)                  ; By default while in insert all changes are one big blob. Be more granular
(setq auto-save-default t)                    ; Nobody likes to loose work, I certainly don't
(setq inhibit-compacting-font-caches t)       ; When there are lots of glyphs, keep them in memory
(setq truncate-string-ellipsis "…")          ; Unicode ellispis are nicer than "...", and also save /precious/ space

(delete-selection-mode 1)                  ; Replace selection when inserting text
(setq line-spacing 0.3)                    ; seems like a nice line spacing balance.
#+end_src

** Autosaves
#+begin_src elisp
(setq auto-save-default t)
(setq auto-save-timeout 20)   ; every 20 secs
(setq auto-save-interval 20)  ; or every 20 keystrokes
#+end_src

** Prettify symbols
#+begin_src elisp
(global-prettify-symbols-mode 1)
#+end_src

** Parenthesis Settings
*** Highlight Matching Bracket
#+begin_src elisp
(require 'paren)
(show-paren-mode 1)
(setq show-paren-delay 0)
(:after xresources
  (set-face-foreground 'show-paren-match (theme-color 'green))
  (set-face-foreground 'show-paren-mismatch "#f00")
  (set-face-attribute 'show-paren-match nil :weight 'extra-bold)
  (set-face-attribute 'show-paren-mismatch nil :weight 'extra-bold))
#+end_src
** Splashpage
*** Remove function menu
Remove the dashboard functions for a more minimal look. See [[https://discourse.doomemacs.org/t/how-to-change-your-splash-screen/57][here]] for details on customising the splashpage.
#+begin_src elisp
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-shortmenu)
#+end_src
*** Maximise frame on load
https://discourse.doomemacs.org/t/maximize-or-fullscreen-emacs-on-startup/135
#+begin_src elisp
(add-hook 'window-setup-hook #'toggle-frame-maximized)
#+end_src
* Custom Commands
** Goto Doom Config
#+begin_src elisp
(defun conf ()
  "Go to config"
  (interactive)
  (dired "~/.nixcfg/users/profiles/doom/doom.d"))
#+end_src
** Goto System Config
#+begin_src elisp
(defun sysconf ()
  "Go to system config"
  (interactive)
  (dired "~/.nixcfg"))
#+end_src

** Goto Home
#+begin_src elisp
(defun home ()
  "Go to home"
  (interactive)
  (dired "~"))
#+end_src
** Goto Documents
#+begin_src elisp
(defun doc ()
  "Go to home"
  (interactive)
  (dired "~/Documents"))
(defun docs ()
  "Go to home"
  (interactive)
  (dired "~/Documents"))
#+end_src
** Goto YouTube scripts
#+begin_src elisp
(defun yt ()
  "Go to yt scripts"
  (interactive)
  (dired "~/Documents/youtube-scripts"))
(defun course ()
  "Go to course scripts"
  (interactive)
  (dired "~/Documents/youtube-scripts/courses"))

(defun appeals ()
  "Go to scripts/appeals"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/appeals"))
(defun scripts/appeals ()
  "Go to scripts/appeals"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/appeals"))

(defun essays ()
  "Go to scripts/essays"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/essays"))
(defun scripts/essays ()
  "Go to scripts/essays"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/essays"))

(defun media-analysis ()
  "Go to scripts/media-analysis"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/media-analysis"))
(defun scripts/media-analysis ()
  "Go to scripts/media-analysis"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/media-analysis"))

(defun news ()
  "Go to scripts/news"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/news"))
(defun scripts/news ()
  "Go to scripts/news"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/news"))

(defun responses ()
  "Go to scripts/responses"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/responses"))
(defun scripts/responses ()
  "Go to scripts/responses"
  (interactive)
  (dired "~/Documents/youtube-scripts/scripts/responses"))
#+end_src

** Goto Notes
#+begin_src elisp
(defun notes ()
  "Go to notes"
  (interactive)
  (dired "~/Documents/notes"))
#+end_src

** Goto liquidzulu.github.io
#+begin_src elisp
(defun web ()
  "Go to liquidzulu.github.io repo"
  (interactive)
  (dired "~/Documents/liquidzulu.github.io"))
(defun webv ()
  "Go to liquidzulu.github.io repo and open terminal"
  (interactive)
  (dired "~/Documents/liquidzulu.github.io")
  (vterm))
#+end_src
** Goto xyzzy
#+begin_src elisp
(defun xyzzy ()
  "Go to xyzzy repo"
  (interactive)
  (dired "~/Documents/xyzzy"))
#+end_src

** Goto capsaicin
#+begin_src elisp
(defun capsaicin ()
  "Go to capsaicin repo"
  (interactive)
  (dired "~/Documents/capsaicin"))
#+end_src

** GOTO scratch buffer
#+begin_src elisp
(defun scratch/org ()
  "Go to the org scratch"
  (interactive)
  (switch-to-buffer (find-file-noselect "~/Documents/xyzzy/scratch/scratch.org" nil nil)))
#+end_src
** goto git repos
#+begin_src elisp
(defun github ()
  "Go to git repos"
  (interactive)
  (dired "~/Documents/github"))
#+end_src

** GOTO writing
#+begin_src elisp
(defun writing ()
  "Go to writing repo"
  (interactive)
  (dired "~/Documents/github/writing"))
#+end_src

* Key Mapping
I use [[https://colemakmods.github.io/mod-dh/][Colemak-DHm]] -- my specific layout can be found [[https://configure.ergodox-ez.com/ergodox-ez/layouts/BO06w/latest/0][here]] -- so remapping of certain core keys, namely motion keys, is required for ergonomics and ease of use.
** global
#+begin_src elisp
;(setq w32-apps-modifier 'hyper)
;(setq w32-lwindow-modifier 'super)
;(setq w32-rwindow-modifier 'hyper)
(setq zulu-scroll-amount 5)

(map!
 "C-l"          #'beginning-of-line
 "C-u"          #'end-of-line
 "C-n"          #'backward-char
 "C-e"          #'forward-char

 "M-l"          #'previous-line
 "M-u"          #'next-line
 "M-n"          #'backward-word
 "M-e"          #'forward-word

 "M-m"          #'(lambda () (interactive) (dotimes (i zulu-scroll-amount) (scroll-up-line)))
 "M-j"          #'(lambda () (interactive) (dotimes (i zulu-scroll-amount) (scroll-down-line)))

 "C-f"          #'org-footnote-action

 "C-c i i"      #'(lambda () (interactive) (insert "#+CAPTION:\n#+NAME:\n[[./images]]") (backward-char) (backward-char) "Insert image")  ; "insert image"
 "C-C i t r"    #'org-table-create-or-convert-from-region
 "C-C i t e"    #'org-table-create-with-table.el

 "s-b" #'ibuffer
 "s-v" #'vterm

 "M-y" #'yank ; I keep accidently pressing this instead of C-y, and I hate it, it breaks everything

 "C-d" #'doom/delete-frame-with-prompt

 "C-x s" #'ace-swap-window

 "C-x M-s" #'(lambda () (interactive) (save-buffer) (org-babel-tangle))

                                        ;"C-RET"    #'(lambda () (interactive) (+org/insert-item-below) (org-return))

 ;; "C-M-x f a"   ;#'helm-bibtex         ; "find article" : opens up helm bibtex for search.
 ;; "C-M-x o n"   ;#'org-noter           ; "org noter"  : opens up org noter in a headline
 ;; "C-M-x r c i" ;#'org-clock-in        ; "routine clock in" : clock in to a habit.
 ;; "C-M-x c b"   ;#'beacon-blink        ; "cursor blink" : makes the beacon-blink
 )
#+end_src

** major/minor modes
#+begin_src elisp
(map! :map markdown-mode-map
      "M-n" #'backward-word) ; used to be markdown-next-link, which breaks the locomotion

(map!
 :map rust-mode-map
 :map python-mode-map
 :map javascript-mode-map
 "C-c C-c C-c"  #'comment-region
 "C-c C-c C-u"  #'uncomment-region)
#+end_src
* abbreviations
#+begin_src elisp
(define-abbrev-table 'global-abbrev-table '(
    ("teh" "the")
    ("acommodate" "accommodate")
    ("accomodate" "accommodate")
    ("acomodate" "accommodate")
    ("ceterus" "ceteris")
    ("cetirus" "ceteris")
    ("addd" "add")
    ("adddd" "add")
    ("_tm" "™")
    ))

(setq-default abbrev-mode t)
#+end_src

* Major modes
#+begin_src elisp
(add-to-list 'auto-mode-alist '("\\.mdx\\'" . markdown-mode))
(add-to-list 'auto-mode-alist '("\\.nix\\'" . nix-mode))
#+end_src
* Only Show Encoding When Not UTF-8
I basically only use UTF-8 so it takes up space for no reason most of the time.
#+begin_src elisp
(defun doom-modeline-conditional-buffer-encoding ()
  (setq-local doom-modeline-buffer-encoding
              (unless (or (eq buffer-file-coding-system 'utf-8-unix)
                          (eq buffer-file-coding-system 'utf-8)))))
(add-hook 'after-change-major-mode-hook #'doom-modeline-conditional-buffer-encoding)
#+end_src
* LSP stuff
** Babel
#+begin_src elisp
(org-babel-do-load-languages
      'org-babel-load-languages
      '(
        (C . t)
        (js . t)
        (rs . t)))
#+end_src

** Astro.js
See https://github.com/emacs-lsp/lsp-mode/issues/3584
#+begin_src elisp
(define-derived-mode astro-mode web-mode "astro")
(setq auto-mode-alist
      (append '((".*\\.astro\\'" . astro-mode))
              auto-mode-alist))

(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration
               '(astro-mode . "astro"))

  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection '("astro-ls" "--stdio"))
                    :activation-fn (lsp-activate-on "astro")
                    :server-id 'astro-ls)))
#+end_src

Enable prettier
#+begin_src elisp
(add-hook 'web-mode-hook #'(lambda ()
                            (:enable-minor-mode
                             '("\\.astro?\\'" . prettier-js-mode))))
#+end_src
** prettier
#+begin_src elisp
(add-hook 'js2-mode-hook 'prettier-js-mode)
(add-hook 'web-mode-hook 'prettier-js-mode)
(add-hook 'astro-mode-hook 'prettier-js-mode)
#+end_src

** python
#+begin_src elisp
(setq auto-mode-alist
      (append '((".*\\.pyx\\'" . cython-mode))
              auto-mode-alist))
#+end_src
* Package Config

** ox-json
#+begin_src elisp
(require 'ox-json)
#+end_src
** org-make-toc
~For tables of contents within orgmode so I dont have to look at md anymore~ This didnt work and was fairly bloaty, no clue what went wrong hopefully I can fix at some point
#+begin_src elisp
                                        ;(add-hook 'org-mode-hook #'org-make-toc-mode) ; automatically update toc
#+end_src
** EAF
#+begin_src elisp
; https://github.com/emacs-eaf/emacs-application-framework/discussions/475#discussioncomment-3035161

#+end_src
